---
:run_mode: :production
:repository_type: :file_system
:repository_name: "notes"
:repository_base: "~"
:pager: "bat -l md"
:picker: "fzf"
:picker_option: "-m"
:editor: "/usr/local/bin/emacsclient"
